progress/home/urls.py
from django.conf.urls import url,include
from . import views

urlpatterns = [
	url(r'^$',views.main,name='main'),
	url(r'^reg/$',views.reg,name='reg'),
	url(r'^login/$',views.log_in,name='login'),
	url(r'^logout/$',views.log_out,name='logout'),
	url(r'^settings/$',views.settings,name='settings'),
	url(r'^register/' +
		'(?P<short_subject_name>[\w]+)/' +
		'(?P<group_name>.+-\d{2}\w)$',
		views.register_table, name='register'
	),
	# url(r'^captcha/', include('captcha.urls')),
	url(r'^statistics/(?P<student_id>\d+)$',views.statistics,name='statistics'),
]

progress/progress/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('home.urls',namespace='home')),
    url(r'^i18n/', include('django.conf.urls.i18n'))
]

progress/home/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

class Subject(models.Model):
	name = models.CharField(max_length = 100)
	short_name = models.CharField(max_length = 10, unique=True, null=True)

	def __str__(self):
		return self.name

class Job(models.Model):
	name = models.CharField(max_length = 512)
	short_name = models.CharField(max_length = 10, null=True)
	subject = models.ForeignKey(Subject)

	def __str__(self):
		return self.name

class Group(models.Model):
	name = models.CharField(max_length=10)
	year = models.IntegerField()
	
	def __str__(self):
		return self.name

class Semester(models.Model):
	group = models.ForeignKey(Group)
	number = models.IntegerField(default=1)
	subjects = models.ManyToManyField(Subject)

	start_date = models.DateField(null=True)
	end_date = models.DateField(null=True)

	def isCurrent(self):
		return self.start_date <= date.today() <= self.end_date

	def __str__(self):
		return self.group.name + ' semester ' + str(self.number)

class Student(models.Model):
	user = models.OneToOneField(User,null=True)
	name = models.CharField(max_length=100)
	patronymic = models.CharField(max_length=100)
	surname = models.CharField(max_length=100)
	group = models.ForeignKey(Group,null=True)

	subjects = models.ManyToManyField(Subject, through='Student_Subject')
	jobs = models.ManyToManyField(Job, through='Log')

	def __str__(self):
		return self.surname + ' ' + self.name

class Teacher(models.Model):
	user = models.OneToOneField(User,null=True)
	name = models.CharField(max_length=100)
	patronymic = models.CharField(max_length=100)
	surname = models.CharField(max_length=100)

	subjects = models.ManyToManyField(Subject)

	def __str__(self):
		return self.surname + ' ' + self.name + ' ' + self.patronymic

class Student_Subject(models.Model):
	student = models.ForeignKey(Student)
	subject = models.ForeignKey(Subject)
	teacher = models.ForeignKey(Teacher)

	def __str__(self):
		return (
			str(self.student) + ' - ' +
			str(self.subject) + ' - ' +
			str(self.teacher.surname)
		)

class Log(models.Model):
	job = models.ForeignKey(Job)
	student = models.ForeignKey(Student)

	mark = models.IntegerField(null=True)
	date = models.DateField()
	confirmed = models.BooleanField(default=False)

	def __str__(self):
		return (
			str(self.student) + ' - ' + 
			str(self.job.subject) + ' - ' + 
			str(self.job)
		)

progress/home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpRequest,HttpResponseRedirect,QueryDict
from django.test.client import Client

import urllib3

from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from django.contrib.auth.models import Group as UsersGroup
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password, make_password
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect
from django.core.exceptions import *
from datetime import date, timedelta
from django import template
from  .models import Group, Student, Teacher, \
					Student_Subject, Subject, Job, Semester, Log
import json

#making available filters in templates
register = template.Library()

def get_current_semesters():
	return list(
			filter(
				(lambda s : s.isCurrent()),
				Semester.objects.all()
			))

def get_current_semester_for(student):
	current_semester = list(
		filter(
			lambda s : s.group == student.group,
			get_current_semesters()
		)
	)
	return current_semester[0] if current_semester else None

def get_subjects_of(semesters):
	subjects = set()
	for semester in semesters:
		subjects |= set(semester.subjects.all())
	return subjects

def how_much_passed(student,semester,week_num):
	week = timedelta(weeks = 1)
	logs = Log.objects.filter(
		student = student,
		date__gte = semester.start_date + (week * week_num) - week,
		date__lt = semester.start_date + (week * week_num)
	)
	return logs.count()

def weeks_in(semester):
	return (semester.end_date - semester.start_date).days // 7

def current_week_of(semester):
	elapsed_days = (date.today() - semester.start_date).days
	elapsed_weeks = elapsed_days // 7
	return elapsed_weeks + 1

def make_plan(jobs_total_count, semester, weeks_statistics):
	next_week_num = current_week_of(semester) + 1
	jobs_left = jobs_total_count - sum(weeks_statistics)
	days_left = (semester.end_date - date.today()).days
	weeks_left = weeks_in(semester) - current_week_of(semester)
	per_week = jobs_left // weeks_left

	plan = list()
	for week_num in range(1,weeks_in(semester)+1):
		if week_num < next_week_num:
			plan.append( None )
		else:
			plan.append( per_week )

	first_step_sum = sum(map(lambda x : 0 if x is None else x,plan))
	diff = jobs_left - first_step_sum

	week_num = next_week_num - 1
	while diff > 0:
		plan[week_num] += 1
		diff -= 1
		week_num += 1

	#connection of lines
	current_week = current_week_of(semester)
	plan[current_week-1] = weeks_statistics[current_week-1]

	return plan

def reg(request):
	#пользователь изменил курс (значение выпадающего списка)
	if request.is_ajax() and request.method=='GET':
		requested_year = request.GET['year']
		groups_objects = Group.objects.filter(year = requested_year)
		groups = [str(group) for group in groups_objects]

		return HttpResponse(json.dumps(groups), content_type='application/json' )

	#регистрация пользователя
	elif request.method=='POST':

		user = User.objects.create_user(
			request.POST['login'],
			email = request.POST['email'],
			password = request.POST['password'],
			first_name = request.POST['name'],
			last_name = request.POST['surname']
		)

		if request.POST['user_type'] == 'student':
			UsersGroup.objects.get(name='Students').user_set.add(user)

			Student.objects.create(
				user = user,
				name = request.POST['name'],
				surname = request.POST['surname'],
				patronymic = request.POST['patronymic'],
				group = Group.objects.get(name=request.POST['group'])
			)

		elif request.POST['user_type'] == 'teacher':

			UsersGroup.objects.get(name='Teachers').user_set.add(user)

			Teacher.objects.create(
				user = user,
				name = request.POST['name'],
				surname = request.POST['surname'],
				patronymic = request.POST['patronymic'],
			)

		return render(request,'home/reg/success.html')

	else:
		#запрос формы регистрации
		years = set( Group.objects.values_list('year',flat=True) )
		years = sorted(list(years))
		return render(request,'home/reg/base.html',locals())

def log_in(request):

	if request.method == 'GET':
		return render(request,'home/login.html')

	elif request.method == 'POST':

		# url: 'https://www.google.com/recaptcha/api/siteverify'
		# type: "GET"
		#
		# request.POST['g-recaptcha-response']
		# "6LeqAQ8TAAAAADlYhA7DjH54shULLYVTYHb_q56l"

		url = 'https://www.google.com/recaptcha/api/siteverify?' + \
				'response='+request.POST['g-recaptcha-response']+ \
				'&secret=6LeqAQ8TAAAAAD-S6bEsThBycfpjMsf-ph0qYsXF'

		resp = urllib3.PoolManager().request('GET',url)
		if json.loads(resp.data.decode('utf-8'))['success']:
			user = authenticate(
				username=request.POST['login'],
				password=request.POST['password']
			)
			if user is not None:
				if user.is_active:
					login(request,user)
					return HttpResponseRedirect(reverse('home:main'))
				else:
					return render(request, 'home/login.html', {
						'error_message':'Ваш аккаунт заблокирован'
						}
					)
			return render(request,'home/login.html',{
				'error_message':'Неверный логин или пароль'
				}
			)
		else:
			return render(request,'home/login.html',{
				'error_message':'Боты не пройдут!'
				}
			)

def log_out(request):
	if request.user.is_authenticated:
		logout(request)
	return HttpResponseRedirect(reverse('home:main'))

def main(request):
	user = request.user
	subjects = None
	jobs = list()
	current_semesters = None
	passed_jobs_ids = None

	user_is_student = hasattr(user,'student')
	user_is_teacher = hasattr(user,'teacher')

	if user_is_student:
		subjects = user.student.subjects.all()
		passed_jobs_ids = [log.job.id for log in Log.objects.filter(student = user.student)]

	if user_is_teacher:
		subjects = set(user.teacher.subjects.all())
		current_semesters = get_current_semesters()
		current_subjects = get_subjects_of(current_semesters)

		subjects &= current_subjects

	if user_is_student or user_is_teacher:
		for subject in subjects:
				for job in subject.job_set.all():
					jobs.append( job )

	if user_is_student:
		return render(request,'home/main/student.html',locals())
	elif user_is_teacher:
		return render(request,'home/main/teacher.html',locals())
	else:
		return render(request,'home/main/base.html',locals())

def settings(request):
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('home:main'))

	user_is_student = hasattr(request.user,'student')
	user_is_teacher = hasattr(request.user,'teacher')

	if request.method == 'POST':

		if  request.is_ajax():

			if request.POST['action'] == 'student_add_subject':

				Student_Subject.objects.create(
					student = Student.objects.get(pk=request.POST['studentid']),
					subject = Subject.objects.get(pk=request.POST['subjectid']),
					teacher = Teacher.objects.get(pk=request.POST['teacherid'])
				)

				return HttpResponse(json.dumps(_('Предмет добавлен')), content_type='application/json')

			elif request.POST['action'] == 'student_delete_subject':

				Student_Subject.objects.get(
					student__id = request.POST['studentid'],
					subject__id = request.POST['subjectid']
				).delete()

				return HttpResponse(json.dumps(_('Предмет удален')),content_type='application/json')

			elif request.POST['action'] == 'student_change_teacher':

				try:
					student_subject_record = Student_Subject.objects.get(
						student__id = request.POST['studentid'],
						subject__id = request.POST['subjectid']
					)
					student_subject_record.teacher = Teacher.objects.get(pk = request.POST['teacherid'])
					student_subject_record.save()

				except ObjectDoesNotExist:
					#если предмет не выбран нет смысла менять преподавателя
					pass

				return HttpResponse(json.dumps(_('Преподаватель изменен')), content_type='application/json')

			elif request.POST['action'] == 'teacher_add_subject':

				subject = Subject.objects.get(pk = request.POST['subjectid'])
				request.user.teacher.subjects.add( subject )
				request.user.teacher.save()

				return HttpResponse(json.dumps(_('Предмет добавлен')), content_type='application/json')

			elif request.POST['action'] == 'teacher_delete_subject':

				teacher = request.user.teacher
				subject = Subject.objects.get(pk = request.POST['subjectid'] )

				student_subject_records = Student_Subject.objects.filter(
					teacher__id = teacher.id,
					subject__id = subject.id
				)

				for record in student_subject_records:
					record.delete()

				teacher.subjects.remove( subject )
				teacher.save()

				return HttpResponse(json.dumps(_('Предмет удален')),content_type='application/json')

			elif request.POST['action'] == 'add_job':

				subject = Subject.objects.get(pk = request.POST['subjectid'])
				Job.objects.create(
					subject = subject,
					name = request.POST['name'],
					short_name = request.POST['short_name']
				)

				return HttpResponse(json.dumps(_('Работа добавлена')),content_type='application/json')

			elif request.POST['action'] == 'delete_job':

				Job.objects.get(pk = request.POST['jobid']).delete()

				return HttpResponse(json.dumps(_('Работа удалена')),content_type='application/json')

			elif request.POST['action'] == 'edit_job_name':

				job = Job.objects.get(pk = request.POST['jobid'])
				job.name = request.POST['new_name']
				job.save()

				return HttpResponse(json.dumps(_('Название изменено')),content_type='application/json')

			elif request.POST['action'] == 'edit_job_short_name':

				job = Job.objects.get(pk = request.POST['jobid'])
				job.short_name = request.POST['new_short_name']
				job.save()

				return HttpResponse(json.dumps(_('Краткое название изменено')),content_type='application/json')

			elif request.POST['action'] == 'add_log_entry':

				studentid = request.POST['studentid']
				jobid = request.POST['jobid']

				log_query_set = Log.objects.filter(student__id = studentid, job__id = jobid)
				log_entry = log_query_set[0] if log_query_set.exists() else None

				if user_is_student:
					if not log_entry:

progress/home/templates/home/base.html
{% load i18n %}
{% load staticfiles %}
{% load filters %}
<!doctype html>
<html>
<head>
	<link href="{% static 'home/logo.ico' %}" rel="icon">
	<!--<link href="{% static 'home/styles.css' %}" rel="stylesheet">-->
	<link href="{% static 'home/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'home/css/custom-style.css' %}" rel="stylesheet">
	<link href="{% static 'home/css/alertify.core.css' %}" rel="stylesheet">
	<link href="{% static 'home/css/alertify.bootstrap.css' %}" rel="stylesheet">
	<link rel="icon" href="{% static 'home/logo.ico' %}" type="image/x-icon">

	<title>{% block title %}{% endblock %}</title>

	<script src="{% static 'home/js/jquery-2.1.4.min.js' %}"></script>
	<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'home/js/alertify.min.js' %}"></script>

	<script src='https://www.google.com/recaptcha/api.js'></script>
	<script src="{% static "home/js/botOrNot.js" %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<header>
		{% block header %}
		<nav>
			{% block menu %}
			<nav class="navbar navbar-default">
				<div class="container">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
						</button>
						<a class="navbar-brand" href="{% url 'home:main' %}"><img id="logo" src="{% static 'home/logo.png' %}"></a>
					</div>
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						<ul class="nav navbar-nav">
							<li><a href="{% url 'home:main' %}">{% trans "Главная" %} <span class="sr-only">(current)</span></a></li>
							{%if user.is_authenticated %}
								<li><a href="{% url 'home:settings' %}">{% trans "Настройки" %}</a></li>
								{% if user|isStudent %}
									<li><a href="{% url 'home:statistics' user.student.id %}">{%trans "Статистика"%}</a></li>
								{% endif %}
							{% endif %}
						</ul>
						<ul class="nav navbar-nav navbar-right">
							{% if request.user.is_authenticated %}
							<li><a href="{% url 'home:logout' %}">{% trans "Выйти" %}<sub> [{{request.user.username}}]</sub></a></li>
							{% else %}
							<li><a href="{% url 'home:login' %}">{% trans "Войти" %}</a></li>
							<li><a href="{% url 'home:reg' %}">{% trans "Регистрация" %}</a></li>
						</ul>
						{% endif %}
					</div>
				</div>
			</nav>
			<script>
				$("a[href='{{request.path}}'").parent("li").attr("class", "active");
			</script>
			{% endblock %}
		</nav>
		{% endblock %}
	</header>
	<main>
		<div class="container">
			{% block main %}
			{% endblock %}
		</div>
	</main>
	<footer class="footer">
		<div class="container">
			{% block footer %}
			<form id='language' action="{% url 'set_language' %}" method="post">
				{% csrf_token %}
				<label for="select" class="col-xs-4 control-label">{% trans "Выберите язык" %}:</label>
				<div class="form-group">
					<input name="next" type="hidden" value="{{ redirect_to }}" />
					<div class="col-xs-1">
						<select name="language" class="form-control language-changer" onchange="this.form.submit()">
							{% get_current_language as LANGUAGE_CODE %}
							{% get_available_languages as LANGUAGES %}
							{% get_language_info_list for LANGUAGES as languages %}
							{% for language in languages %}
							<option value="{{ language.code }}"
							{% if language.code == LANGUAGE_CODE %}
							selected="selected"
							{% endif %}
							>
							{{ language.name_local }} ({{ language.code }})
						</option>
						{% endfor %}
						</select>
					</div>
				</div>
			</form>
			{% endblock %}
		</div>
	</footer>
</body>
</html>

progress/home/templates/home/main.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load filters %}
{% load staticfiles %}
{% block title %} {% trans "Главная" %} {% endblock %}
{% block scripts %}
	<script src="{% static "home/js/js-cookie.js" %}"></script>
	<script src="{% static "home/js/settings.js" %}"></script>
{% endblock %}

{% block main %}
	{% if error_message %}
		<span class='error'> {{error_message}} </span>
	{% else %}

		{% if user|isStudent %}
			{% block student %}{% endblock %}

		{% elif user|isTeacher %}
			{% block teacher %}{% endblock %}
			
		{% endif %}

	{% endif %} {#error message#}

{% endblock %}

progress/home/templates/home/reg-student.html
{% load i18n %}

<form id='student' action="{% url 'home:reg' %}" method="POST">
	{% csrf_token %}
		<input class='student_reg' type="text" name="login"		placeholder="{% trans "Логин" %}"
			oninput='validateLogin($(this))'>
		<br>
		<input class='student_reg' type="email"name="email"		placeholder="{% trans "E-mail" %}"
			oninput='validateEmail($(this))'>
		<br>
		<input class='student_reg' type="text" name="surname"	placeholder="{% trans "Фамилия" %}"
			oninput='validateWord($(this))'>
		<br>
		<input class='student_reg' type="text" name="name"		placeholder="{% trans "Имя" %}"
			oninput='validateWord($(this))'>
		<br>
		<input class='student_reg' type="text" name="patronymic"placeholder="{% trans "Отчество" %}"
			oninput='validateWord($(this))'>
		<br>

		<span>{% trans "Курс" %}:</span>
		<select id="year" name="year" onchange="loadGroupsFrom({% url 'home:reg' %})">
			{% for year in years %}
				<option value="{{year}}">{{year}}</option>
			{% endfor %}
		</select>
		<span>{% trans "Группа" %}:</span>
		<select id="group" name="group">
			<script>loadGroupsFrom({% url 'home:reg' %})</script>
		</select>
		<br>
		<input class='student_reg' type="password" placeholder="{% trans "Пароль" %}" name="password"
			id="student"
			oninput='validatePassword($(this))'>
		<br>
		<input class='student_reg' type="password" name = 'password_rep' placeholder="{% trans "Повторить пароль" %}"
			oninput='validatePasswordConfirmation($(this),"student")'>
		<br>
		<input type="hidden" name="user_type" value="student">
		<input id = 'reg_student' type="submit" value="{% trans "Зарегистрироваться" %}">
</form>

progress/home/templates/home/register.html
{% extends 'home/base.html' %}
{% load i18n %}
{% load filters %}
{% load staticfiles %}

{% block scripts %}
	<script src="{% static "home/js/js-cookie.js" %}"></script>
	<script src="{% static "home/js/settings.js" %}"></script>
	<script src="{% static "home/js/register.js" %}"></script>
{% endblock %}

{% block main %}
	{% if error_message %}
		<span class='error'> {{error_message}} </span>
	{% else %}

		<span>{% trans "Ведомость по дисциплине" %} {{subject.name}}</span><br>
		<span>{% trans "Группа" %} {{group.name}} </span><br>

		<table>
			<tr class='bottom-border'>
				<td class='right-border'></td>
				{% for job in subject.job_set.all %}
					<td class='centered'>
						{{job.short_name}}
					</td>
				{% endfor %}
			</tr>
			{% for student in group.student_set.all %}
				<tr>
					<td class='right-border'> {{student}} </td>
					{% for job in subject.job_set.all %}
						<td class='centered'>
							<input type='checkbox' class='no-margin' id='{{student.id}}-{{job.id}}'
									{% if student|log_entry_confirmed:job %}
										checked='checked'
									{% endif %}
									{% if not request.user|isTeacher %}
										disabled='disabled'
									{% endif %}
							>
							<span class='font12'>
								{% if student|log_entry_mark:job %}
									{{student|log_entry_mark:job}}
								{% endif %}
							</span>
						</td>
						{% if request.user|isTeacher %}
							<script>
								$('#{{student.id}}-{{job.id}}').on('click', function() {
									toggleLogRecord(
										{% url 'home:settings' %},
										{{ student.id }},
										{{ job.id }},
										$(this).prop('checked')
									)
								})
							</script>
						{% endif %}
					{% endfor %}
					<td class='font14'>
						<a href='#' id='pencil{{student.id}}'> &#9998; </a> {# pencil #}
						<div id='editor{{student.id}}' class='hidden centered popup'>
							<span>{{student}}</span>
							<span> - {{subject.short_name}} </span>
							<table  class='editor'>
								{% for job in subject.job_set.all %}
									<tr id='job{{job.id}}'>
										<td class='font14'> {{job.name}} </td>
										<td>
											<input type='number' min='0' max='100'
												placeholder='{% trans "Оценка" %}'
												id='mark-for{{job.id}}of{{student.id}}'
												{% if student|log_entry_confirmed:job %}
													value='{{ student|log_entry_mark:job }}'
												{% else %}
													disabled='disabled'
												{% endif %}

											>
										</td>
										<td>
											<input type='date' id='date-for{{job.id}}of{{student.id}}'
												{% if student|log_entry_confirmed:job %}
													value='{{ student|log_entry_date:job }}'
												{% else %}
													disabled='disabled'
												{% endif %}
											>
										</td>
										<script>
											$('#mark-for{{job.id}}of{{student.id}}').on('keyup mouseup', function() {
												changeMark(
													'{% url "home:register" subject.short_name group.name %}',
													{{student.id}},
													{{job.id}},
													$(this).val()
												)
											})
											$('#date-for{{job.id}}of{{student.id}}').on('change', function() {
												changeDate(
													'{% url "home:register" subject.short_name group.name %}',
													{{student.id}},
													{{job.id}},
													$(this).val()
												)
											})
										</script>
									</tr>
								{% endfor %}
							</table>
							<input id='edit-ok-{{student.id}}' type='button' value='OK'>
							<script>
								$('#edit-ok-{{student.id}}').on('click',function(){
										$("#editor{{student.id}}").fadeOut(300);
										setTimeout(function(){location.reload()},300)
									})
							</script>
						</div>
						<script>
							$('#pencil{{student.id}}').on('click', function () {
								$('#editor{{student.id}}').fadeIn(300)
							})
						</script>
					</td>
				</tr>
			{% endfor %}
		</table>

	{% endif %}{# error_message #}

{% endblock %}

progress/home/templates/home/student-settings.html
{% extends 'home/settings.html' %}
{% load i18n %}
{% load filters %}

{% block student %}
	<fieldset>
		<legend>{% trans "Предметы" %}</legend>
		{% for subject in subjects %}
			<label>
				<input type='checkbox'
						id='{{subject.id}}'
						{% if subject in user.student.subjects.all %}
							checked
						{% endif %}
				>
				{{subject.name}}
			</label>
			&nbsp;
			<select data-subjectid='{{subject.id}}'>
				{% for teacher in subject.teacher_set.all %}
					<option value='{{teacher.id}}'
							{% if teacher == user.student|teacherOf:subject %}
								selected
							{% endif %}
					>
						{{teacher}}
					</option>
				{% endfor %}
			</select>
			<br>
			<script>
				// handlers

				$('input#{{subject.id}}').on('click',function() {
					toggleStudentSubjectRecord(
						{% url 'home:settings' %},							{# link for ajax request #}
						{{user.student.id}},								{# student id #}
						$(this).attr('id'),									{# subject id #}
						$('select[data-subjectid={{subject.id}}]').val(), 	{# teacher id #}
						$(this).prop('checked')
					)
				})

				$('select[data-subjectid={{subject.id}}]').on('change',function(){
					changeTeacher(
						{% url 'home:settings' %},
						{{user.student.id}},
						$(this).attr('data-subjectid'),
						$(this).val()
					)
				})
			</script>
		{% endfor %}
	</fieldset>
{% endblock %}

progress/home/templates/home/teacher-main.html
{% extends 'home/main.html' %}
{% load i18n %}
{% load filters %}
{% load staticfiles %}

{% block teacher %}
	<span> {{ user.teacher.name }} {{ user.teacher.surname }}</span>
	<fieldset>
		<legend>{% trans "Предметы" %}</legend>
		<ul class='outer'>
			{% for subject in subjects %}
				<li>
					{{subject.name}}
					<ul>
					{% for semester in currentSemesters %}
						{% if subject in semester.subjects.all %}
							<li>
								<a href='{% url "home:register" subject.short_name semester.group.name %}'>
									{{ semester.group.name }}
								</a>
							</li>
						{% endif %}
					{% endfor %}
					</ul>
				</li>
			{% endfor %}
			<script>
				$('.drop_down').on('click',function () {
					$(this).children().slideToggle(100)
				})
			</script>
		</ul>
	</fieldset>

	<fieldset>
		<legend>{% trans "Работы" %}</legend>
			<ul class='outer'>
				{% for subject in subjects %}
					<li>
						{{subject.name}}
						<table class='left-border'>
							{% for job in subject.job_set.all %}
								<tr>
									<td>{{job.name}}</td>
								
									<td>
										<a href='#'
											onclick="editJobName(
												{% url 'home:settings' %},
												{{job.id}},
												'{% trans "Изменть название" %}',
												'{{job.name}}'
											)"
										>
											&#9998; {# pencil #}
										</a>
									</td>

									<td> {{job.short_name}} </td>

									<td>
										<a href='#'
											onclick="editJobShortName(
												{% url 'home:settings' %},
												{{job.id}},
												'{% trans "Изменть краткое название" %}',
												'{{job.short_name}}'
											)"
										>
											&#9998; {# pencil #}
										</a>
									</td>
									<td>
										<a href='#'
											onclick="deleteJob(
												{% url 'home:settings' %},
												{{job.id}},
												'{% trans "Удалить" %} {{job.name}}?'
											)"
										>
											&#10005; {# cross #}
										</a>
									</td>
								</tr>
							{% endfor %}
						</table>
					</li>
				{% endfor %}
			</ul>

			<label>{% trans "Предмет" %}</label>
			<select id='subject'>
				{% for subject in subjects %}
					<option value='{{subject.id}}'>{{subject.name}}</option>
				{% endfor %}
			</select>

			<input type='text' name='name' placeholder='{% trans "Название" %}'
					class='wide'>
			<input type='text' name='short_name' placeholder='{% trans "Кратко" %}*'
					class='short' title='{% trans "Например Лаб.3" %}'>
			<input id='add-button' type='button' value='{% trans "Добавить" %}'>

			<script>
				$('#add-button').on('click',function () {
					addJob(
						{% url "home:settings" %},
						$('select#subject').val(),
						$('input[name=name]').val(),
						$('input[name=short_name]').val()
					)
				})
			</script>

			<span class='block font14'>
				*
				{% trans "Рекомендуется заполнить все поля" %}
				"{% trans "Кратко" %}"
				{% trans "так как они используются в таблцие" %}
			</span>

	</fieldset>
{% endblock teacher %}